onEvent('block.registry', event => {
  event.create('roboss:ae2_trophy').material('rock').hardness(1).displayName('Applied Energistic 2 Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:twilightforest_trophy').material('rock').hardness(1).displayName('Twilight Forest Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:create_trophy').material('rock').hardness(1).displayName('Create Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:industrialforegoing_trophy').material('rock').hardness(1).displayName('Industrial Foregoing Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:mekanism_trophy').material('rock').hardness(1).displayName('Mekanism Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:thermal_trophy').material('rock').hardness(1).displayName('Thermal Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:extendedcrafting_trophy').material('rock').hardness(1).displayName('Extended Crafting Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:miscellaneous_trophy').material('rock').hardness(1).displayName('Miscellaneous Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:botania_trophy').material('rock').hardness(1).displayName('Botania Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:powergen_trophy').material('rock').hardness(1).displayName('PowerGen Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:rftools_trophy').material('rock').hardness(1).displayName('RFTools Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:projecte_trophy').material('rock').hardness(1).displayName('ProjectE Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
  event.create('roboss:immersiveengineering_trophy').material('rock').hardness(1).displayName('Immersive Engineering Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).box(3,0,3,13,18,13, true)
})