onEvent('rei.hide.items', event => {
    event.hide([
                //lead
                'immersiveengineering:deepslate_ore_lead', 
                'immersiveengineering:raw_block_lead', 
                'immersiveengineering:raw_lead', 
                'immersiveengineering:storage_lead', 
                'immersiveengineering:ingot_lead', 
                'immersiveengineering:dust_lead', 
                'immersiveengineering:plate_lead', 
                'immersiveengineering:nugget_lead', 
                'immersiveengineering:slab_storage_lead', 
                'create:crushed_lead_ore', 
                'mekanism:nugget_lead', 
                'mekanism:dust_lead', 
                'mekanism:ingot_lead', 
                'mekanism:block_lead', 
                'mekanism:raw_lead', 
                'mekanism:block_raw_lead', 
                'mekanism:deepslate_lead_ore', 
                'mekanism:lead_ore', 
                'immersiveengineering:ore_lead',
                Item.of('ae2:facade', '{item:"mekanism:block_lead"}'),
                Item.of('ae2:facade', '{item:"mekanism:block_raw_lead"}'),
                Item.of('ae2:facade', '{item:"mekanism:lead_ore"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:ore_lead"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:raw_block_lead"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:storage_lead"}'),
                Item.of('ae2:facade', '{item:"mekanism:deepslate_lead_ore"}'),
                //copper
                'create:copper_sheet', 
                'immersiveengineering:plate_copper', 
                'immersiveengineering:wire_copper', 
                'immersiveengineering:dust_copper', 
                'mekanism:dust_copper', 
                'create:copper_nugget', 
                'tconstruct:copper_nugget', 
                'immersiveengineering:nugget_copper', 
                'cyclic:copper_nugget',
                'create:crushed_copper_ore',
                //bronze
                'mekanism:dust_bronze', 
                'mekanism:ingot_bronze', 
                'mekanism:nugget_bronze', 
                'mekanism:block_bronze'
            ])
  })